---
title: "GSE145085"
author: "Gabriel"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(GEOquery)
library(limma)
library(edgeR)

library(dendextend)

library(factoextra); library(FactoMineR)
```

```{r}
id <- 'GSE145085'

geo <- getGEO(id)

gse <- geo[[1]]
pdata <- pData(gse)

#=========carregar counts========
rnaseq <- getGEOSuppFiles(id)
rnaseq  <- read.delim('GSE145085/GSE145085_CountMatrix.txt')
rnaseq$Length <- NULL

colnames(rnaseq) <- gsub('\\.', '-', colnames(rnaseq))
pdata$title <- tolower(pdata$title)

all(pdata$title == colnames(rnaseq[-1]))
#==========conferir anotação=========
rnaseq.genes <- data.frame(rnaseq$Geneid)

library(org.Hs.eg.db)
genes <- AnnotationDbi::select(org.Hs.eg.db, keys = rnaseq.genes$rnaseq.Geneid , keytype = 'ENSEMBL', columns = c("ENTREZID", "SYMBOL"))

genes <- genes[!duplicated(genes$ENSEMBL),]
rnaseq.genes <- left_join(rnaseq.genes, genes, by=c("rnaseq.Geneid" = 'ENSEMBL'))

rnaseq <- column_to_rownames(rnaseq, var='Geneid')
```

```{r}
dge <- DGEList(rnaseq)
dge$samples$group <- pdata$`treatment:ch1`
dge$genes <- genes

cpm <- cpm(dge)
lcpm <- cpm(dge, log=T)

dge$samples

```
#low expressed
```{r}
dge <- dge[!is.na(dge$genes$ENTREZID),]

keep.exprs <- filterByExpr(dge, group = dge$samples$group)

dge.filter <- dge[keep.exprs, keep.lib.sizes=F]
```

#NORM
```{r}
dge.filter <- calcNormFactors(dge.filter, method = 'TMM')

plotMDS(cpm(dge.filter, log=T))

```

#clusterização
```{r}
pca <- PCA(t(cpm(dge.filter, log=F)), graph = F)

fviz_pca_ind(pca,
             mean.point=F, 
             geom.ind='point', pointshape=21, pointsize=3,
             fill.ind=pdata$`treatment:ch1`,
             addEllipses = T, ellipse.type='confidence')+
  theme_classic()
  

dist <- dist(t(dge.filter$counts)) 
hc <- hclust(dist) 
dend <- as.dendrogram(hc) 
dend %>% 
  color_labels(labels = colnames(dge.filter$counts[,which(pdata$`treatment:ch1` == unique(pdata$`treatment:ch1`)[1])]), col='blue') %>% 
  color_labels(labels = colnames(dge.filter$counts[,which(pdata$`treatment:ch1` == unique(pdata$`treatment:ch1`)[2])]), col='red') %>%
  plot() 
legend('topright', legend=c(unique(pdata$`treatment:ch1`)), col=c('blue', 'darkred', 'orange2'), pch=c(20,20,20))
```

```{r}
design.rnaseq <- model.matrix(~ 0 + dge$samples$group)
colnames(design.rnaseq)
colnames(design.rnaseq) <- c("Cisplatin", "Control")
contrasts.rnaseq <- makeContrasts(Cisplatin - Control, levels = colnames(design.rnaseq))

v <- voom(dge.filter, design = design.rnaseq, plot=T)

vfit <- lmFit(v, design.rnaseq)
vfit <- contrasts.fit(vfit, contrasts=contrasts.rnaseq)
efit <- eBayes(vfit)
plotSA(efit)

summary(decideTests(efit, p.value = 0.05, lfc = 1.5))

topTable(efit, number=Inf) %>% 
  filter(adj.P.Val < .05, abs(logFC) > 1.5) %>% 
  View()

topTable(efit, number = Inf) %>% writexl::write_xlsx('organoid_fc.xlsx')
```

